// shell/pages.js — GENERATED by scripts/gen-shell.mjs from docs/commands.json.
// DO NOT EDIT BY HAND: regenerate with `node scripts/gen-shell.mjs` (wired into
// the docs build). The command dataset comes from the Dhall schemas, so the
// route table is derived from the schemas too.
//
// Imported by both shell/shell.js (browser ESM) and scripts/ssg.mjs (Node ESM).
//
// SLOT NAME == one per route, and every slot resolves to the single MFE module
// '/fx-core/shell/mfe/fx-core-page.js' via the import map. Unique per-route slots are required: a
// shared slot name would send @mfe/core's reconcile down its transplant path and
// show stale content on cross-page navigation.

export const BASE_PATH = "/fx-core";
export const MFE_MODULE = "/fx-core/shell/mfe/fx-core-page.js";

export const PAGES = [
  {
    "slug": "",
    "path": "/fx-core/",
    "slot": "fx-core-index",
    "dir": "",
    "title": "fx-core — command reference",
    "description": "The fx-core command reference: every fixpoint-linux coreutil, its usage, arguments, types and defaults — generated from the Dhall schemas that define them."
  },
  {
    "slug": "basename",
    "path": "/fx-core/basename",
    "slot": "fx-cmd-basename",
    "dir": "basename",
    "title": "fx-basename — fx-core",
    "description": "strip directories and any suffix from file names"
  },
  {
    "slug": "cat",
    "path": "/fx-core/cat",
    "slot": "fx-cmd-cat",
    "dir": "cat",
    "title": "fx-cat — fx-core",
    "description": "concatenate FILEs (or stdin) to stdout, bytes to bytes"
  },
  {
    "slug": "chgrp",
    "path": "/fx-core/chgrp",
    "slot": "fx-cmd-chgrp",
    "dir": "chgrp",
    "title": "fx-chgrp — fx-core",
    "description": "change the group ownership of files (datalog-backed stat rows)"
  },
  {
    "slug": "chmod",
    "path": "/fx-core/chmod",
    "slot": "fx-cmd-chmod",
    "dir": "chmod",
    "title": "fx-chmod — fx-core",
    "description": "change file mode bits, journaled through the derivation log"
  },
  {
    "slug": "chown",
    "path": "/fx-core/chown",
    "slot": "fx-cmd-chown",
    "dir": "chown",
    "title": "fx-chown — fx-core",
    "description": "change the owner and/or group of files (datalog-backed stat rows)"
  },
  {
    "slug": "cksum",
    "path": "/fx-core/cksum",
    "slot": "fx-cmd-cksum",
    "dir": "cksum",
    "title": "fx-cksum — fx-core",
    "description": "print CRC checksum (POSIX) and byte count for each FILE"
  },
  {
    "slug": "comm",
    "path": "/fx-core/comm",
    "slot": "fx-cmd-comm",
    "dir": "comm",
    "title": "fx-comm — fx-core",
    "description": "compare two sorted files line by line (three-column output)"
  },
  {
    "slug": "cp",
    "path": "/fx-core/cp",
    "slot": "fx-cmd-cp",
    "dir": "cp",
    "title": "fx-cp — fx-core",
    "description": "copy files, capturing originals to CAS before mutating"
  },
  {
    "slug": "date",
    "path": "/fx-core/date",
    "slot": "fx-cmd-date",
    "dir": "date",
    "title": "fx-date — fx-core",
    "description": "print or set the system date and time (UTC)"
  },
  {
    "slug": "df",
    "path": "/fx-core/df",
    "slot": "fx-cmd-df",
    "dir": "df",
    "title": "fx-df — fx-core",
    "description": "report filesystem usage in 1K blocks via statvfs"
  },
  {
    "slug": "diff",
    "path": "/fx-core/diff",
    "slot": "fx-cmd-diff",
    "dir": "diff",
    "title": "fx-diff — fx-core",
    "description": "compare two files (or trees, -r) line by line"
  },
  {
    "slug": "dirname",
    "path": "/fx-core/dirname",
    "slot": "fx-cmd-dirname",
    "dir": "dirname",
    "title": "fx-dirname — fx-core",
    "description": "strip the last component from a file name"
  },
  {
    "slug": "du",
    "path": "/fx-core/du",
    "slot": "fx-cmd-du",
    "dir": "du",
    "title": "fx-du — fx-core",
    "description": "estimate file space usage as Datalog-backed stat rows"
  },
  {
    "slug": "echo",
    "path": "/fx-core/echo",
    "slot": "fx-cmd-echo",
    "dir": "echo",
    "title": "fx-echo — fx-core",
    "description": "print the given STRINGs to stdout, newline-terminated"
  },
  {
    "slug": "env",
    "path": "/fx-core/env",
    "slot": "fx-cmd-env",
    "dir": "env",
    "title": "fx-env — fx-core",
    "description": "print, filter or modify the environment, then run nothing (print form)"
  },
  {
    "slug": "expand",
    "path": "/fx-core/expand",
    "slot": "fx-cmd-expand",
    "dir": "expand",
    "title": "fx-expand — fx-core",
    "description": "convert tabs in FILEs (or stdin) to spaces"
  },
  {
    "slug": "find",
    "path": "/fx-core/find",
    "slot": "fx-cmd-find",
    "dir": "find",
    "title": "fx-find — fx-core",
    "description": "walk a directory closure via Datalog reachability from ROOT"
  },
  {
    "slug": "grep",
    "path": "/fx-core/grep",
    "slot": "fx-cmd-grep",
    "dir": "grep",
    "title": "fx-grep — fx-core",
    "description": "print lines of files under ROOT matching a regex PATTERN"
  },
  {
    "slug": "head",
    "path": "/fx-core/head",
    "slot": "fx-cmd-head",
    "dir": "head",
    "title": "fx-head — fx-core",
    "description": "print the first N lines (-n, default 10) of FILEs (or stdin)"
  },
  {
    "slug": "hostname",
    "path": "/fx-core/hostname",
    "slot": "fx-cmd-hostname",
    "dir": "hostname",
    "title": "fx-hostname — fx-core",
    "description": "print the system's host name"
  },
  {
    "slug": "id",
    "path": "/fx-core/id",
    "slot": "fx-cmd-id",
    "dir": "id",
    "title": "fx-id — fx-core",
    "description": "print user and group identity for USER (or the caller)"
  },
  {
    "slug": "link",
    "path": "/fx-core/link",
    "slot": "fx-cmd-link",
    "dir": "link",
    "title": "fx-link — fx-core",
    "description": "create a hard link OLD -> NEW via linkat, journaled"
  },
  {
    "slug": "ln",
    "path": "/fx-core/ln",
    "slot": "fx-cmd-ln",
    "dir": "ln",
    "title": "fx-ln — fx-core",
    "description": "create links between files (-s for symbolic)"
  },
  {
    "slug": "ls",
    "path": "/fx-core/ls",
    "slot": "fx-cmd-ls",
    "dir": "ls",
    "title": "fx-ls — fx-core",
    "description": "list a directory's entries as Datalog-backed stat rows"
  },
  {
    "slug": "md5sum",
    "path": "/fx-core/md5sum",
    "slot": "fx-cmd-md5sum",
    "dir": "md5sum",
    "title": "fx-md5sum — fx-core",
    "description": "print or check MD5 (128-bit) checksums"
  },
  {
    "slug": "mkdir",
    "path": "/fx-core/mkdir",
    "slot": "fx-cmd-mkdir",
    "dir": "mkdir",
    "title": "fx-mkdir — fx-core",
    "description": "create directories (-p for parents), journaled"
  },
  {
    "slug": "mkfifo",
    "path": "/fx-core/mkfifo",
    "slot": "fx-cmd-mkfifo",
    "dir": "mkfifo",
    "title": "fx-mkfifo — fx-core",
    "description": "create FIFOs with mkfifo(3), -m sets the mode"
  },
  {
    "slug": "mv",
    "path": "/fx-core/mv",
    "slot": "fx-cmd-mv",
    "dir": "mv",
    "title": "fx-mv — fx-core",
    "description": "rename SOURCE to DEST, or move SOURCE into DIRECTORY"
  },
  {
    "slug": "nl",
    "path": "/fx-core/nl",
    "slot": "fx-cmd-nl",
    "dir": "nl",
    "title": "fx-nl — fx-core",
    "description": "number lines of a file or stdin (GNU nl)"
  },
  {
    "slug": "paste",
    "path": "/fx-core/paste",
    "slot": "fx-cmd-paste",
    "dir": "paste",
    "title": "fx-paste — fx-core",
    "description": "merge corresponding or subsequent lines of files (GNU paste)"
  },
  {
    "slug": "ps",
    "path": "/fx-core/ps",
    "slot": "fx-cmd-ps",
    "dir": "ps",
    "title": "fx-ps — fx-core",
    "description": "snapshot running processes as a datalog-backed view"
  },
  {
    "slug": "realpath",
    "path": "/fx-core/realpath",
    "slot": "fx-cmd-realpath",
    "dir": "realpath",
    "title": "fx-realpath — fx-core",
    "description": "print the resolved absolute file name"
  },
  {
    "slug": "rm",
    "path": "/fx-core/rm",
    "slot": "fx-cmd-rm",
    "dir": "rm",
    "title": "fx-rm — fx-core",
    "description": "remove files or directories (-r), journaled with CAS capture"
  },
  {
    "slug": "rmdir",
    "path": "/fx-core/rmdir",
    "slot": "fx-cmd-rmdir",
    "dir": "rmdir",
    "title": "fx-rmdir — fx-core",
    "description": "remove empty directories, journaled"
  },
  {
    "slug": "seq",
    "path": "/fx-core/seq",
    "slot": "fx-cmd-seq",
    "dir": "seq",
    "title": "fx-seq — fx-core",
    "description": "print a sequence of numbers FIRST..LAST (step INC)"
  },
  {
    "slug": "sha1sum",
    "path": "/fx-core/sha1sum",
    "slot": "fx-cmd-sha1sum",
    "dir": "sha1sum",
    "title": "fx-sha1sum — fx-core",
    "description": "print or check SHA-1 (160-bit) checksums"
  },
  {
    "slug": "sha224sum",
    "path": "/fx-core/sha224sum",
    "slot": "fx-cmd-sha224sum",
    "dir": "sha224sum",
    "title": "fx-sha224sum — fx-core",
    "description": "print or check SHA-224 checksums"
  },
  {
    "slug": "sha256sum",
    "path": "/fx-core/sha256sum",
    "slot": "fx-cmd-sha256sum",
    "dir": "sha256sum",
    "title": "fx-sha256sum — fx-core",
    "description": "print or check SHA-256 checksums"
  },
  {
    "slug": "sha384sum",
    "path": "/fx-core/sha384sum",
    "slot": "fx-cmd-sha384sum",
    "dir": "sha384sum",
    "title": "fx-sha384sum — fx-core",
    "description": "print or check SHA-384 checksums"
  },
  {
    "slug": "sha512sum",
    "path": "/fx-core/sha512sum",
    "slot": "fx-cmd-sha512sum",
    "dir": "sha512sum",
    "title": "fx-sha512sum — fx-core",
    "description": "print or check SHA-512 checksums"
  },
  {
    "slug": "sort",
    "path": "/fx-core/sort",
    "slot": "fx-cmd-sort",
    "dir": "sort",
    "title": "fx-sort — fx-core",
    "description": "sort lines (numeric, reverse, unique) as Datalog-backed rows"
  },
  {
    "slug": "sum",
    "path": "/fx-core/sum",
    "slot": "fx-cmd-sum",
    "dir": "sum",
    "title": "fx-sum — fx-core",
    "description": "print checksum and block count for each FILE (-s SysV)"
  },
  {
    "slug": "tail",
    "path": "/fx-core/tail",
    "slot": "fx-cmd-tail",
    "dir": "tail",
    "title": "fx-tail — fx-core",
    "description": "print the last N lines (-n, default 10) of FILEs (or stdin)"
  },
  {
    "slug": "tee",
    "path": "/fx-core/tee",
    "slot": "fx-cmd-tee",
    "dir": "tee",
    "title": "fx-tee — fx-core",
    "description": "copy stdin to each FILE and to stdout (-a appends)"
  },
  {
    "slug": "top",
    "path": "/fx-core/top",
    "slot": "fx-cmd-top",
    "dir": "top",
    "title": "fx-top — fx-core",
    "description": "single-shot process ranking by total cpu ticks or memory"
  },
  {
    "slug": "touch",
    "path": "/fx-core/touch",
    "slot": "fx-cmd-touch",
    "dir": "touch",
    "title": "fx-touch — fx-core",
    "description": "create files or update timestamps, journaled"
  },
  {
    "slug": "tree",
    "path": "/fx-core/tree",
    "slot": "fx-cmd-tree",
    "dir": "tree",
    "title": "fx-tree — fx-core",
    "description": "render a directory closure as a tree (Datalog descent)"
  },
  {
    "slug": "truncate",
    "path": "/fx-core/truncate",
    "slot": "fx-cmd-truncate",
    "dir": "truncate",
    "title": "fx-truncate — fx-core",
    "description": "shrink or extend a file to SIZE (-r REF), CAS-captured"
  },
  {
    "slug": "uname",
    "path": "/fx-core/uname",
    "slot": "fx-cmd-uname",
    "dir": "uname",
    "title": "fx-uname — fx-core",
    "description": "print system information (-a: all)"
  },
  {
    "slug": "uniq",
    "path": "/fx-core/uniq",
    "slot": "fx-cmd-uniq",
    "dir": "uniq",
    "title": "fx-uniq — fx-core",
    "description": "filter repeated adjacent lines in sorted input (-c counts)"
  },
  {
    "slug": "unlink",
    "path": "/fx-core/unlink",
    "slot": "fx-cmd-unlink",
    "dir": "unlink",
    "title": "fx-unlink — fx-core",
    "description": "delete a name and possibly the file it refers to"
  },
  {
    "slug": "wc",
    "path": "/fx-core/wc",
    "slot": "fx-cmd-wc",
    "dir": "wc",
    "title": "fx-wc — fx-core",
    "description": "print newline, word and byte counts for each FILE"
  },
  {
    "slug": "what",
    "path": "/fx-core/what",
    "slot": "fx-cmd-what",
    "dir": "what",
    "title": "fx-what — fx-core",
    "description": "query which package owns a rootfs PATH (provenance)"
  },
  {
    "slug": "whoami",
    "path": "/fx-core/whoami",
    "slot": "fx-cmd-whoami",
    "dir": "whoami",
    "title": "fx-whoami — fx-core",
    "description": "print the effective user name"
  },
  {
    "slug": "why",
    "path": "/fx-core/why",
    "slot": "fx-cmd-why",
    "dir": "why",
    "title": "fx-why — fx-core",
    "description": "explain why a package is in the store (provenance)"
  },
  {
    "slug": "yes",
    "path": "/fx-core/yes",
    "slot": "fx-cmd-yes",
    "dir": "yes",
    "title": "fx-yes — fx-core",
    "description": "repeatedly output STRING (or 'y'), one per line, until killed"
  }
];

export const CONTENT_PAGES = PAGES;
