#!/usr/bin/env node
/**
 * scripts/gen-shell.mjs — generate the MFE shell artifacts for the fx-core docs
 * site from the command dataset.
 *
 * The route table is DERIVED, not hand-written: `docs/commands.json` (generated
 * from the Dhall schemas by `zig build docs`) is the single source of truth, so
 * adding a command to its schema adds its page here with no other edit.
 *
 * Emits (all under shell/):
 *   shell/pages.js                  the canonical route table (imported by both
 *                                   shell/shell.js in the browser and ssg.mjs in Node)
 *   shell/templates/<slot>.html     one route template per page, each carrying a
 *                                   UNIQUE data-mfe slot (unique slots are required
 *                                   by @mfe/core's reconcile — a shared slot across
 *                                   routes would take the transplant path and show
 *                                   stale content on cross-page nav)
 *
 * Run from the repo root:
 *   node scripts/gen-shell.mjs
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DATASET = join(ROOT, 'docs', 'commands.json');
const SHELL = join(ROOT, 'shell');
const TEMPLATES = join(SHELL, 'templates');

/** The site's deploy base path (its own directory on the host). */
const BASE_PATH = '/fx-core';
/** The ONE MFE module every slot resolves to. */
const MFE_MODULE = `${BASE_PATH}/shell/mfe/fx-core-page.js`;

const log = (m) => console.log(`[gen-shell] ${m}`);

const dataset = JSON.parse(readFileSync(DATASET, 'utf8'));
const commands = [...dataset.commands].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

const pages = [
  {
    slug: '',
    path: `${BASE_PATH}/`,
    slot: 'fx-core-index',
    dir: '',
    title: 'fx-core — command reference',
    description:
      'The fx-core command reference: every fixpoint-linux coreutil, its usage, arguments, types and defaults — generated from the Dhall schemas that define them.',
  },
  ...commands.map((c) => ({
    slug: c.name,
    path: `${BASE_PATH}/${c.name}`,
    slot: `fx-cmd-${c.name}`,
    dir: c.name,
    title: `fx-${c.name} — fx-core`,
    description: c.doc,
  })),
];

// ---- shell/pages.js --------------------------------------------------------

const pagesJs = `// shell/pages.js — GENERATED by scripts/gen-shell.mjs from docs/commands.json.
// DO NOT EDIT BY HAND: regenerate with \`node scripts/gen-shell.mjs\` (wired into
// the docs build). The command dataset comes from the Dhall schemas, so the
// route table is derived from the schemas too.
//
// Imported by both shell/shell.js (browser ESM) and scripts/ssg.mjs (Node ESM).
//
// SLOT NAME == one per route, and every slot resolves to the single MFE module
// '${MFE_MODULE}' via the import map. Unique per-route slots are required: a
// shared slot name would send @mfe/core's reconcile down its transplant path and
// show stale content on cross-page navigation.

export const BASE_PATH = ${JSON.stringify(BASE_PATH)};
export const MFE_MODULE = ${JSON.stringify(MFE_MODULE)};

export const PAGES = ${JSON.stringify(pages, null, 2)};

export const CONTENT_PAGES = PAGES;
`;

writeFileSync(join(SHELL, 'pages.js'), pagesJs);
log(`wrote shell/pages.js (${pages.length} routes)`);

// ---- shell/templates/<slot>.html -------------------------------------------

rmSync(TEMPLATES, { recursive: true, force: true });
mkdirSync(TEMPLATES, { recursive: true });

for (const page of pages) {
  const html = `<!--
  shell/templates/${page.slot}.html — route template for '${page.path}'.
  GENERATED by scripts/gen-shell.mjs; edit the generator, not this file.
-->
<div class="fixpoint-root">
  <div data-mfe="${page.slot}"></div>
</div>
`;
  writeFileSync(join(TEMPLATES, `${page.slot}.html`), html);
}

log(`wrote ${pages.length} templates to shell/templates/`);
